export enum QueueName {
  INVOICE_QUEUE = 'INVOICE_QUEUE',
  NOTIFICATION_QUEUE = 'NOTIFICATION_QUEUE',
  PUSH_QUEUE = 'PUSH_QUEUE',
  EMAIL_QUEUE = 'EMAIL_QUEUE',
  SMS_QUEUE = 'SMS_QUEUE',
  PAYMENT_QUEUE = 'PAYMENT_QUEUE',
}

export enum InvoiceJobName {
  CREATE_BULK_INVOICE_JOB = 'CREATE_BULK_INVOICE_JOB',
}